se/urls.py
from django.conf.urls import include, url
from . import views

app_name='se' 
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^our-profile$', views.profile, name='our-profile'),
    url(r'^our-approach$', views.approach, name='our-approach'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail') # testing purpose
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from se import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', views.home, name='home'),
    url(r'^', include('se.urls')),
    # url(r'^', include('se.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

se/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

class Profile(models.Model):
	fname = models.CharField(max_length=125, default="")
	lname = models.CharField(max_length=125, null=True)
	description = models.TextField(null=True)

	def __str__(self):
		return self.fname + " " + self.lname

se/views.py
from django.shortcuts import get_object_or_404, redirect, render

from django.http import HttpResponse
from django.contrib.auth.models import User

def home(request):
	context = locals()
	template = "se/home.html"
	return render(request, template ,context)

def profile(request):
	context = locals()
	template = "se/profile.html"
	return render(request, template ,context)

def approach(request):
	context = locals()
	template = "se/approach.html"
	return render(request, template ,context)

def detail(request, question_id=0):
	context = locals()	
	template = "se/home.html"
	html_ = "d f"
	html_va = "<b>jjn knjjkk <b>"
	# print(request)
	return render(request, template ,context)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'se/images/logo/favicon.ico' %}">

    <title>SE</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'se/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'se/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'se/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'se/css/sticky-footer-navbar.css' %}" rel="stylesheet">
    
  </head>

  <body>
  {% include 'navbar.html' %}
    <main role="main">
    {% block content %}
    {% endblock %}
      <!-- <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2>Heading </h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container --> 

    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">&copy; Sachin Engineers 2017</span>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'se/js/popper.min.js' %}"></script>
    <script src="{% static 'se/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Sachin Engineers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        {% url 'se:home' as home %}
        {% url 'se:our-profile' as profile %}
        {% url 'se:our-approach' as approach %}
          <li class="nav-item {% if request.path == home %} active {% endif %}">
            <a class="nav-link" href="{% url 'se:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% if request.path == home %} active {% endif %}">
            <a class="nav-link" href="#">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About Us</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'se:our-profile' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'se:our-approach' %}">Our Approach</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

templates/se/approach.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
    <div class="row">
      	<div class="col-md-12">
          <h3>Our Approach</h3>
          <p>We are customer centric company due to which our entire effort revolves around our customers and we take pride in providing our customers with complete solutions which allows them to utilize the product in its entirety with ease.<br><p><b>We understand and value your precious time than to worry about your cutting tools.</b></p> </p>
          <p >Therefore, It's our job to provide best solution to your cutting tools.We are completely passionate in our area of expertise. We love solving complexities involved in building new cutting tools as per design specified by our customers. But most of all, we love in delivering best to our customers in terms of product quality and saving them money.  </p>
          <p class="text-darken-1">In order to outperform in this competitive market, We knew we had to be different... and that we are. We have our unique methods to process cutting tools in a best possible way so as to meet customer satisfaction.</p>
      	</div>
    </div>
    
    <hr>
      
  </div> <!-- /container -->
{% endblock %}

templates/se/home.html
{% extends 'base.html' %}
{% block content %}
<!-- <style type="text/css">
	body {
  		padding-top: 3rem;
  	}
</style> -->
<!-- Main jumbotron for a primary marketing message or call to action -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
        	<div class="carousel-item active">
	            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
	            <div class="container">
	              <div class="carousel-caption text-left">
	                <h1>Example headline.</h1>
	                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
	              </div>
	            </div>
          	</div>
          	<div class="carousel-item">
	            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
	            <div class="container">
	              <div class="carousel-caption">
	                <h1>Another example headline.</h1>
	                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
	              </div>
	            </div>
          	</div>
          	<div class="carousel-item">
	            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
	            <div class="container">
	              <div class="carousel-caption text-right">
	                <h1>One more for good measure.</h1>
	                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
	              </div>
	            </div>
          	</div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
{% endblock %}

templates/se/profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-md-12">
          <h2>Profile</h2>
          <p><b>Sachin Engineers</b> was started in 2002 in order to fulfill the needs of growing industrial and manufacturing sector. We have also gained full customer satisfaction by providing best quality services and products to them. We initiated our operations over a decade ago in Delhi-NCR region and gradually expanded it throughout the country. </p>
          <p>We resharpen all major brands of carbide and HSS tools used for industrial purpose, modify them and grind specials as our daily business so as to avoid unnecessary cost involved in buying new cutting tool which in turn leads to build more trust with our customers. We also manufactures new tool as per design given by our customer.</p>
          <h5>FOUNDER AND THE MOTIVATOR</h5>
          <p class="text-darken-1">We are a small team led by <b>Mr. Arbind Kumar Kushwaha</b> who is the founder, chairman of Sachin Engineers. He has more than 20 years of rich experience in the industrial and manufacturing sector. We have been one of the best in our areas of work because of the immense knowledge and experience that he possess. 
          </p>
        </div>
    </div>
    
    <hr>
      
  </div> <!-- /container -->
{% endblock %}